site_name: ScamAway Docs
repo_url: https://github.com/Xenorio/ScamAway-API
edit_uri: https://github.com/Xenorio/ScamAway-Docs/edit/main/docs/
site_description: Documentation for the ScamAway Discord bot
plugins:
  - section-index
  - search
  - render_swagger
theme:
  name: material
  logo: https://github.com/Xenorio/ScamAway/raw/main/logo.png
  favicon: https://github.com/Xenorio/ScamAway/raw/main/logo.png
  font: Open Sans
  palette:
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji
